version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    groups:
      python:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: "/desktop"
    schedule:
      interval: monthly
    groups:
      desktop:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: "/desktop/src-tauri"
    schedule:
      interval: monthly
    groups:
      tauri:
        patterns: ["*"]
