#!/usr/bin/env bash
# Shared WSL-native storage layout. Keep large/IO-heavy artifacts off /mnt/*.
SOAI_DATA_HOME="${SOAI_DATA_HOME:-$HOME/.local/share/sovereign-ai}"
SOAI_STATE_DIR="${SOAI_STATE_DIR:-$SOAI_DATA_HOME/state}"
SOAI_MODEL_DIR="${SOAI_MODEL_DIR:-$SOAI_DATA_HOME/models}"
SOAI_CACHE_DIR="${SOAI_CACHE_DIR:-$SOAI_DATA_HOME/cache}"
SOAI_RUNTIME_DIR="${SOAI_RUNTIME_DIR:-$SOAI_DATA_HOME/runtimes}"
SOAI_OUTPUT_DIR="${SOAI_OUTPUT_DIR:-$SOAI_DATA_HOME/outputs}"
SOAI_ENV_DIR="${SOAI_ENV_DIR:-$SOAI_DATA_HOME/envs}"

export SOAI_DATA_HOME SOAI_STATE_DIR SOAI_MODEL_DIR SOAI_CACHE_DIR
export SOAI_RUNTIME_DIR SOAI_OUTPUT_DIR SOAI_ENV_DIR
export SOVEREIGN_STATE_DIR="$SOAI_STATE_DIR"
export SOVEREIGN_MODEL_DIR="$SOAI_MODEL_DIR"
export SOVEREIGN_CACHE_DIR="$SOAI_CACHE_DIR"
export SOVEREIGN_RUNTIME_DIR="$SOAI_RUNTIME_DIR"
export HF_HOME="${HF_HOME:-$SOAI_CACHE_DIR/huggingface}"
export UV_CACHE_DIR="${UV_CACHE_DIR:-$SOAI_CACHE_DIR/uv}"

mkdir -p "$SOAI_STATE_DIR" "$SOAI_MODEL_DIR" "$SOAI_CACHE_DIR" \
  "$SOAI_RUNTIME_DIR" "$SOAI_OUTPUT_DIR" "$SOAI_ENV_DIR"
